# ================== [GET DATA MAHASISWA] ===========================

# Melakukan get data mahasiswa
GET http://localhost:8080/api/v1/mahasiswa

###
# Ambil data mahasiswa dan prodinya berdasarkan id mahasiswa
GET http://localhost:8080/api/v1/mahasiswa/data/5

# ================== [ GET DATA PRODI] ===========================

###
# Melakukan get data prodi
GET http://localhost:8080/api/v1/prodi

###
# Melakukan get semua data prodi dan mahasiswa berdasarkan prodi id
GET http://localhost:8080/api/v1/prodi/data/1

# ================== [RELASI TABEL] ===========================

# Melakukan join antar tabel get data mahasiswa 
###
GET http://localhost:8080/api/v1/mahasiswa/prodi

# Ambil semua data mahasiswa dan prodi berdasarkan id prodinya
###
GET http://localhost:8080/api/v1/mahasiswa/prodi/1

# ================== [SAVE DATA MAHASISWA] ===========================

###
# masukan data mahasiswa
POST http://localhost:8080/api/v1/mahasiswa
Content-Type: application/json

{
    "name": "John Doe",
    "npm": "2208100024",
    "email": "john@gmail.com",
    "prodiId": 2
}

###
# Masukan data prodi
POST http://localhost:8080/api/v1/prodi
Content-Type: application/json

{
    "prodi": "Teknologi Informasi",
    "prodiId": "1"
}

# ================== [UPDATE DATA MAHASISWA] ===========================
# Update data mahasiswa berdasarkan id
###
PATCH http://localhost:8080/api/v1/mahasiswa/6
Content-Type: application/json

{
    "name": "Joko setiawan",
    "email": "jokoasik@gmail.com",
    "npm": "220810045",
    "prodiId": 2
}

# ================== [DELETED DATA MAHASISWA] ===========================
###
DELETE  http://localhost:8080/api/v1/mahasiswa/9